/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ImageRouteImport } from './routes/image'
import { Route as CoderRouteImport } from './routes/coder'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicImageRouteImport } from './routes/api/public/image'
import { Route as ApiPublicCoderRouteImport } from './routes/api/public/coder'
import { Route as ApiPublicChatRouteImport } from './routes/api/public/chat'

const ImageRoute = ImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => rootRouteImport,
} as any)
const CoderRoute = CoderRouteImport.update({
  id: '/coder',
  path: '/coder',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicImageRoute = ApiPublicImageRouteImport.update({
  id: '/api/public/image',
  path: '/api/public/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCoderRoute = ApiPublicCoderRouteImport.update({
  id: '/api/public/coder',
  path: '/api/public/coder',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicChatRoute = ApiPublicChatRouteImport.update({
  id: '/api/public/chat',
  path: '/api/public/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/image': typeof ImageRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/coder': typeof ApiPublicCoderRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/image': typeof ImageRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/coder': typeof ApiPublicCoderRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/coder': typeof CoderRoute
  '/image': typeof ImageRoute
  '/api/public/chat': typeof ApiPublicChatRoute
  '/api/public/coder': typeof ApiPublicCoderRoute
  '/api/public/image': typeof ApiPublicImageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/coder'
    | '/image'
    | '/api/public/chat'
    | '/api/public/coder'
    | '/api/public/image'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/coder'
    | '/image'
    | '/api/public/chat'
    | '/api/public/coder'
    | '/api/public/image'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/coder'
    | '/image'
    | '/api/public/chat'
    | '/api/public/coder'
    | '/api/public/image'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  CoderRoute: typeof CoderRoute
  ImageRoute: typeof ImageRoute
  ApiPublicChatRoute: typeof ApiPublicChatRoute
  ApiPublicCoderRoute: typeof ApiPublicCoderRoute
  ApiPublicImageRoute: typeof ApiPublicImageRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/image': {
      id: '/image'
      path: '/image'
      fullPath: '/image'
      preLoaderRoute: typeof ImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coder': {
      id: '/coder'
      path: '/coder'
      fullPath: '/coder'
      preLoaderRoute: typeof CoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/image': {
      id: '/api/public/image'
      path: '/api/public/image'
      fullPath: '/api/public/image'
      preLoaderRoute: typeof ApiPublicImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/coder': {
      id: '/api/public/coder'
      path: '/api/public/coder'
      fullPath: '/api/public/coder'
      preLoaderRoute: typeof ApiPublicCoderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/chat': {
      id: '/api/public/chat'
      path: '/api/public/chat'
      fullPath: '/api/public/chat'
      preLoaderRoute: typeof ApiPublicChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  CoderRoute: CoderRoute,
  ImageRoute: ImageRoute,
  ApiPublicChatRoute: ApiPublicChatRoute,
  ApiPublicCoderRoute: ApiPublicCoderRoute,
  ApiPublicImageRoute: ApiPublicImageRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
